name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      rancher:
        image: rancher/rancher:latest
        ports:
          - 80:80
          - 443:443
        env:
          CATTLE_BOOTSTRAP_PASSWORD: admin
          CATTLE_BOOTSTRAP_TYPE: admin
        options: >-
          --privileged
          --restart=unless-stopped
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Wait for Rancher
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' https://localhost)" != "200" ]]; do sleep 5; done'
          
      - name: Run Cypress tests
        run: npm run test
        env:
          CYPRESS_BASE_URL: https://localhost
          
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots