name: Infrastructure and Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ui
          - api
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate SSH Key
        run: |
          ssh-keygen -t ed25519 -f ~/.ssh/gh_actions -q -N ""
          echo "SSH_PUBLIC_KEY=$(cat ~/.ssh/gh_actions.pub)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.6'

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Attempt VM Cleanup
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform destroy -auto-approve \
            -var "project=${{ secrets.GCP_PROJECT_ID }}" \
            -var "zone=us-central1-a" \
            -var "machine_type=e2-medium" \
            -var "ssh_public_key=${{ env.SSH_PUBLIC_KEY }}" || true

      - name: Terraform Apply
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform apply -auto-approve \
            -var "project=${{ secrets.GCP_PROJECT_ID }}" \
            -var "zone=us-central1-a" \
            -var "machine_type=e2-medium" \
            -var "ssh_public_key=${{ env.SSH_PUBLIC_KEY }}"

      - name: Get VM IP
        id: get_ip
        working-directory: terraform
        run: |
          bash ../scripts/get_ip.sh > ip_output.txt
          IP=$(grep "Cleaned IP:" ip_output.txt | cut -d' ' -f3)
          echo "Found IP: $IP"
          echo "ip=$IP" >> "$GITHUB_OUTPUT"

      - name: Setup Go
        if: inputs.test_suite == 'api' || inputs.test_suite == 'all'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: api-tests/go.sum

      - name: Setup Node.js
        if: inputs.test_suite == 'ui' || inputs.test_suite == 'all'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'ui-tests/package-lock.json'

      - name: Wait for Rancher
        run: |
          timeout=300
          while ! curl -k https://${{ steps.get_ip.outputs.ip }} -s -f -o /dev/null && [ $timeout -gt 0 ]; do
            echo "Waiting for Rancher to be ready..."
            sleep 10
            timeout=$((timeout - 10))
          done
          if [ $timeout -le 0 ]; then
            echo "Timeout waiting for Rancher"
            exit 1
          fi

      - name: API Tests
        if: inputs.test_suite == 'api' || inputs.test_suite == 'all'
        working-directory: api-tests
        env:
          RANCHER_URL: https://${{ steps.get_ip.outputs.ip }}
        run: |
          go mod download
          go test -v ./...

      - name: UI Tests
        if: inputs.test_suite == 'ui' || inputs.test_suite == 'all'
        uses: cypress-io/github-action@v6
        with:
          working-directory: ui-tests
          browser: chrome
        env:
          CYPRESS_BASE_URL: https://${{ steps.get_ip.outputs.ip }}
          CYPRESS_VERIFY_SSL: false
          NODE_TLS_REJECT_UNAUTHORIZED: '0'

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ui-tests/cypress/videos
            ui-tests/cypress/screenshots
            api-tests/test-reports

      - name: Terraform Destroy
        if: always()
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform destroy -auto-approve \
            -var "project=${{ secrets.GCP_PROJECT_ID }}" \
            -var "zone=us-central1-a" \
            -var "machine_type=e2-medium" \
            -var "ssh_public_key=${{ env.SSH_PUBLIC_KEY }}"