name: Rancher Test Suite

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select the test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ui
          - api
  push:
    branches: [main, 'test/**', 'feature/**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ADMIN_PASSWORD: ${{ secrets.RANCHER_ADMIN_PASSWORD }}
      RANCHER_URL: https://localhost:8443

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove Existing Docker Packages
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true

      - name: Install Prerequisites for Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

      - name: Add Docker’s Official GPG Key
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

      - name: Set Up Docker Repository
        run: |
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Install Docker Engine
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Verify Docker Installation
        run: |
          sudo docker run hello-world

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.6' # Specify your Terraform version

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Delete existing VM
        continue-on-error: true
        run: |
          gcloud auth activate-service-account --key-file <(echo '${{ secrets.GCP_SA_KEY }}')
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud compute instances delete test-vm --zone=us-central1-a --quiet
        
      - name: Debug GCP Credentials
        run: |
            echo '${{ secrets.GCP_SA_KEY }}' | jq 'with_entries(select(.key | test("^(type|project_id|client_email)$")))' || echo "Invalid JSON format"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Terraform Apply
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform apply -auto-approve \
            -var "project=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=us-central1" \
            -var "zone=us-central1-a" \
            -var "machine_type=e2-medium" \
            -var 'tags=["rancher-server","http-server","https-server"]'

      - name: Retrieve VM IP
        id: get_ip
        working-directory: terraform
        run: |
          ip=$(terraform output -raw instance_ip | tr -d '%')
          echo "ip=$ip" >> $GITHUB_OUTPUT

      - name: Wait for Rancher API to be Ready
        run: |
          echo "Waiting for Rancher API at ${{ steps.get_ip.outputs.ip }}..."
          until curl -sk https://${{ steps.get_ip.outputs.ip }}/ping > /dev/null 2>&1; do
            echo "Rancher API not ready yet. Retrying in 10 seconds..."
            sleep 10
          done
          echo "Rancher API is available."

      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: api-tests/go.sum

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'ui-tests/package-lock.json'

      # Conditional Steps for API Tests
      - name: Setup API Tests
        if: ${{ github.event.inputs.test_suite == 'api' || github.event.inputs.test_suite == 'all' }}
        working-directory: api-tests
        run: |
          # Assuming config.yml is already created by the script on VM
          echo "Config.yml is already created by rancher-local.sh on the VM"
          go mod download

      - name: Run API Tests
        if: ${{ github.event.inputs.test_suite == 'api' || github.event.inputs.test_suite == 'all' }}
        working-directory: api-tests
        run: go test -v ./...

      # Conditional Steps for UI Tests
      - name: Install UI Dependencies
        if: ${{ github.event.inputs.test_suite == 'ui' || github.event.inputs.test_suite == 'all' }}
        working-directory: ui-tests
        run: npm ci

      - name: Run UI Tests
        if: ${{ github.event.inputs.test_suite == 'ui' || github.event.inputs.test_suite == 'all' }}
        uses: cypress-io/github-action@v6
        with:
          working-directory: ui-tests
          browser: chrome
        env:
          CYPRESS_BASE_URL: ${{ steps.get_ip.outputs.ip }}
          CYPRESS_RANCHER_URL: ${{ steps.get_ip.outputs.ip }}
          CYPRESS_VERIFY_SSL: false
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
          CYPRESS_CHROME_WEB_SECURITY: false
          CYPRESS_AUTH_TOKEN: ${{ secrets.CYPRESS_AUTH_TOKEN }}

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ui-tests/cypress/videos
            ui-tests/cypress/screenshots
            api-tests/test-reports

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Cleanup Rancher
        if: always()
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.get_ip.outputs.ip }} "./scripts/rancher-local.sh stop"
        env:
          GITHUB_ENV: $GITHUB_ENV

      - name: Terraform Destroy
        if: always()
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform destroy -auto-approve \
            -var "project=${{ secrets.GCP_PROJECT_ID }}" \
            -var "credentials_file=credentials.json"