name: Rancher Test Suite

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select the test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ui
          - api
  push:
    branches: [main, 'test/**', 'feature/**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ADMIN_PASSWORD: ${{ secrets.RANCHER_ADMIN_PASSWORD }}
      RANCHER_URL: https://localhost:8443

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Docker
      - name: Remove Existing Docker Packages
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true

      - name: Install Prerequisites for Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

      - name: Add Docker’s Official GPG Key
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

      - name: Set Up Docker Repository
        run: |
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Install Docker Engine
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Verify Docker Installation
        run: |
          sudo docker run hello-world

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.6'

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > "$HOME/gcloud-key.json"
          gcloud auth activate-service-account --key-file="$HOME/gcloud-key.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Enable Necessary APIs
      - name: Enable Required GCP APIs
        run: |
          gcloud services enable compute.googleapis.com
          gcloud services enable storage.googleapis.com
          gcloud services enable iam.googleapis.com
          gcloud services enable serviceusage.googleapis.com
          # Add any other necessary APIs here

      # Wait for APIs to be enabled
      - name: Wait for APIs to be Enabled
        run: |
          for i in {1..10}; do
            gcloud services list --enabled --filter="NAME:compute.googleapis.com" && break
            echo "Compute Engine API not enabled yet. Retrying in 10 seconds..."
            sleep 10
          done
          for i in {1..10}; do
            gcloud services list --enabled --filter="NAME:storage.googleapis.com" && break
            echo "Storage API not enabled yet. Retrying in 10 seconds..."
            sleep 10
          done
          # Repeat for other APIs if necessary

      # Verify Compute Engine API and IAM
      - name: Verify Compute Engine API and IAM
        run: |
          gcloud services list --enabled --filter="NAME:compute.googleapis.com"
          gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }} \
            --flatten="bindings[].members" \
            --filter="bindings.members:terraform-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com" \
            --format="table(bindings.role)"

      # Terraform Init
      - name: Terraform Init
        working-directory: terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json
        run: terraform init

      # Apply Terraform Configuration
      - name: Terraform Apply
        working-directory: terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: terraform apply -auto-approve \
          -var "project=${{ secrets.GCP_PROJECT_ID }}" \
          -var "region=us-central1" \
          -var "zone=us-central1-a" \
          -var 'tags=["rancher-server","http-server","https-server"]' \
          -var "machine_type=e2-medium" \
          -var "image_project=debian-cloud" \
          -var "image_family=debian-11" \
          -var "network=default" \
          -var "subnetwork=default"

      # Retrieve VM IP
      - name: Retrieve VM IP
        id: get_ip
        working-directory: terraform
        run: echo "ip=$(terraform output -raw instance_ip)" >> $GITHUB_OUTPUT

      # Wait for Rancher API
      - name: Wait for Rancher API to be Ready
        run: |
          echo "Waiting for Rancher API at ${{ steps.get_ip.outputs.ip }}..."
          until curl -sk https://${{ steps.get_ip.outputs.ip }}/ping > /dev/null 2>&1; do
            echo "Rancher API not ready yet. Retrying in 10 seconds..."
            sleep 10
          done
          echo "Rancher API is available."

      # Set up Go Environment
      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: api-tests/go.sum

      # Set up Node.js Environment
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'ui-tests/package-lock.json'

      # Conditional API Tests
      - name: Setup API Tests
        if: ${{ github.event.inputs.test_suite == 'api' || github.event.inputs.test_suite == 'all' }}
        working-directory: api-tests
        run: |
          echo "Preparing API tests..."
          go mod download

      - name: Run API Tests
        if: ${{ github.event.inputs.test_suite == 'api' || github.event.inputs.test_suite == 'all' }}
        working-directory: api-tests
        run: go test -v ./...

      # Conditional UI Tests
      - name: Install UI Dependencies
        if: ${{ github.event.inputs.test_suite == 'ui' || github.event.inputs.test_suite == 'all' }}
        working-directory: ui-tests
        run: npm ci

      - name: Run UI Tests
        if: ${{ github.event.inputs.test_suite == 'ui' || github.event.inputs.test_suite == 'all' }}
        uses: cypress-io/github-action@v6
        with:
          working-directory: ui-tests
          browser: chrome
        env:
          CYPRESS_BASE_URL: ${{ steps.get_ip.outputs.ip }}
          CYPRESS_RANCHER_URL: ${{ steps.get_ip.outputs.ip }}
          CYPRESS_VERIFY_SSL: false
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
          CYPRESS_CHROME_WEB_SECURITY: false
          CYPRESS_AUTH_TOKEN: ${{ secrets.CYPRESS_AUTH_TOKEN }}

      # Upload Test Artifacts
      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ui-tests/cypress/videos
            ui-tests/cypress/screenshots
            api-tests/test-reports

      # Set up SSH Key
      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Cleanup Rancher
      - name: Cleanup Rancher
        if: always()
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.get_ip.outputs.ip }} "./scripts/rancher-local.sh stop"

      # Destroy Terraform Resources
      - name: Terraform Destroy
        if: always()
        working-directory: terraform
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          terraform destroy -auto-approve \
            -var "project=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=us-central1" \
            -var "zone=us-central1-a"
