name: Rancher Test Suite

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select the test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ui
          - api
  push:
    branches: [main, 'test/**', 'feature/**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ADMIN_PASSWORD: ${{ secrets.RANCHER_ADMIN_PASSWORD }}
      RANCHER_URL: https://localhost:8443

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Make Rancher Script Executable
        run: chmod +x scripts/rancher-local.sh

      - name: Start Rancher and Generate API Tokens
        run: ./scripts/rancher-local.sh start
        env:
          GITHUB_ENV: $GITHUB_ENV
          ADMIN_PASSWORD: ${{ env.ADMIN_PASSWORD }}
          RANCHER_URL: ${{ env.RANCHER_URL }}

      # At this point, API_TOKEN, API_USERNAME, and CYPRESS_AUTH_TOKEN are set

      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
          cache-dependency-path: api-tests/go.sum

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'ui-tests/package-lock.json'

      # Conditional Steps for API Tests
      - name: Setup API Tests
        if: ${{ github.event.inputs.test_suite == 'api' || github.event.inputs.test_suite == 'all' }}
        working-directory: api-tests
        run: |
          # Assuming config.yml is already created by the script
          echo "Config.yml already created by rancher-local.sh"
          go mod download

      - name: Run API Tests
        if: ${{ github.event.inputs.test_suite == 'api' || github.event.inputs.test_suite == 'all' }}
        working-directory: api-tests
        run: go test -v ./...

      # Conditional Steps for UI Tests
      - name: Install UI Dependencies
        if: ${{ github.event.inputs.test_suite == 'ui' || github.event.inputs.test_suite == 'all' }}
        working-directory: ui-tests
        run: npm ci

      - name: Run UI Tests
        if: ${{ github.event.inputs.test_suite == 'ui' || github.event.inputs.test_suite == 'all' }}
        uses: cypress-io/github-action@v6
        with:
          working-directory: ui-tests
          browser: chrome
        env:
          CYPRESS_BASE_URL: ${{ env.RANCHER_URL }}
          CYPRESS_RANCHER_URL: ${{ env.RANCHER_URL }}
          CYPRESS_VERIFY_SSL: false
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
          CYPRESS_CHROME_WEB_SECURITY: false
          CYPRESS_AUTH_TOKEN: ${{ env.CYPRESS_AUTH_TOKEN }}

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            ui-tests/cypress/videos
            ui-tests/cypress/screenshots
            api-tests/test-reports

      - name: Cleanup Rancher
        if: always()
        run: ./scripts/rancher-local.sh stop
        env:
          GITHUB_ENV: $GITHUB_ENV