on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rancher:
        image: rancher/rancher:latest
        ports:
          - 0:443
        env:
          CATTLE_BOOTSTRAP_PASSWORD: ${{ secrets.RANCHER_ADMIN_PASSWORD }}
        options: --privileged --restart=unless-stopped

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate SSL certificate
        run: |
          mkdir -p ./certs
          openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 \
            -nodes -keyout ./certs/server.key -out ./certs/server.crt \
            -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost"

      - name: Wait for Rancher to be ready
        run: |
          echo "Waiting for Rancher container to initialize..."
          for i in {1..12}; do
            STATUS=$(docker inspect -f "{{.State.Status}}" $(docker ps -q --filter "ancestor=rancher/rancher:latest"))
            if [ "$STATUS" = "running" ]; then
              UI_STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" https://localhost:8443)
              if [ "$UI_STATUS" -eq 200 ]; then
                echo "Rancher is ready!"
                exit 0
              fi
            fi
            echo "Still waiting... ($((i * 5)) seconds elapsed)"
            sleep 5
          done
          echo "Error: Rancher failed to initialize within 60 seconds."
          exit 1

      - name: Initialize Rancher
        run: |
          FIRST_LOGIN_TOKEN=$(curl -k -s "https://localhost:$RANCHER_PORT/v3-public/localProviders/local?action=login" \
            -H 'content-type: application/json' \
            --data-raw "{\"username\":\"admin\",\"password\":\"${{ secrets.RANCHER_ADMIN_PASSWORD }}\"}" | jq -r .token)
          echo "CYPRESS_AUTH_TOKEN=$FIRST_LOGIN_TOKEN" >> $GITHUB_ENV

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=https://localhost:$RANCHER_PORT
        env:
          CYPRESS_VERIFY_SSL: false

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
